name: socialx
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  fpdart: ^1.1.1
  supabase_flutter: ^2.9.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  uuid: ^4.3.3
  intl: ^0.20.2
  internet_connection_checker_plus: ^2.2.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  animated_notch_bottom_bar: ^1.0.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  flutter_stripe: ^10.1.1
  path_provider: ^2.1.5
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1



# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular-400.ttf
        - asset: fonts/Montserrat-Bold-700.ttf
        - asset: fonts/Montserrat-Medium-500.ttf